<?php
//Email
$_['email_title']    = '[GrandCMS] Schedule DB Backup';
$_['email_message']    = '<h3>GrandCMS Schedule Backup</h3><hr />This email is generated by GrandCMS Scheduled DB Backup.';

// Text
$_['text_setup']     = '<hr />This backup had been set up for ';
$_['text_date']     = '<hr />This backup schedule has been executed at ';
$_['text_next']     = '<hr />Next backup is set to run at ';
$_['text_hr']     = '<hr />';
?>